# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:22-alpine AS build
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY package*.json ./
# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install

# Copy the rest of the app files
COPY . .

# Build the app
RUN npm run build
# ==== RUN =======
# Set the env to "development"
ENV NODE_ENV development
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "npx", "serve", "build" ]
