import { useEffect, useState } from 'react';
import axios from 'axios';
import TextInput from "../components/Input/Input.component";
import { Button } from "@mui/material";

const SecureLink = () => {
  const [keyValid, setKeyValid] = useState<boolean>(false);
  const [otp, setOtp] = useState<string>("");

  // This component will be used to display the upload download page for users with secure links without the need to login.
  // The secure link will be generated by the server and sent to the user to access the link.
  // the page url will contain a key that will be used to verify the secure link. https://example.com/:key
  // once this page is loaded it will make a request to the server to verify the secure link and if the link is valid server will send an OTP to the user to verify the user.
  // Once the user is verified the user will be able to access the upload download page.
  // The user will have access to the page for a limited time and after that, the user will have to request a new secure link to access the page.

  const key = window.location.pathname.split('/')[1];

  const requestOtp = async () => {
    console.log("Requesting OTP");
    // make a request to the server to send OTP to the user

    // check env variable to get the server url
    const baseUrl = import.meta.env.MODE === "production"
      ? import.meta.env.VITE_API_BASE_URL_PROD
      : import.meta.env.VITE_API_BASE_URL_DEV;

    console.log({ baseUrl });

    try {
      const response = await axios({
        method: "POST",
        url: `${baseUrl}/key/request-code`,
        data: { key },
        headers: {
          "Content-Type": "application/json"
        }
      })

      console.log({ response });

      if (response.data && response.data.success) {
        setKeyValid(true);
      }
    } catch (error) {
      console.log(error);
    }
  }

  const verifyOtp = (otp: string) => async () => {
    console.log("Verifying OTP");
    // make a request to the server to verify the OTP

    // check env variable to get the server url
    const baseUrl = import.meta.env.MODE === "production"
      ? import.meta.env.VITE_API_BASE_URL_PROD
      : import.meta.env.VITE_API_BASE_URL_DEV;

    console.log({ baseUrl });

    try {
      const response = await axios({
        method: "POST",
        url: `${baseUrl}/key/verify`,
        data: { key, otp },
        headers: {
          "Content-Type": "application/json"
        }
      })

      console.log({ response });

      if (response.data && response.data.success) {
        // redirect the user to the upload download page
        alert("OTP Verified");
      } else {
        alert("Invalid OTP");
      }
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    // verify the secure link
    // if the secure link is valid, send OTP to the user
    // if the secure link is invalid, redirect the user to the error page
    requestOtp();
  }, [key]);

  return (
    <>
      {(!keyValid) && <div>Invalid Secure Link</div>}
      {keyValid && (
        <>
          <TextInput
            label="Enter OTP"
            name="otp"
            value={otp}
            placeholder="Enter OTP"
            handleChange={(e) => setOtp(e.target.value)}
            required
            autoFocus
          />
          <Button
            variant="contained"
            color="primary"
            onClick={verifyOtp(otp)}
          >
            Verify
          </Button>
          <Button
            variant="contained"
            color="secondary"
            onClick={requestOtp}
          >
            Resend OTP
          </Button>
        </>
      )}
    </>
  )
}

export default SecureLink